services:
  - type: web
    name: flight-api
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "uvicorn challenge.api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9